title = "openBVE Documentation"
theme = "openbve_documentation"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
removePathAccents = true

relativeURLs = true
uglyURLs = true

disableKinds = ["page", "404", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

[params]
logoimage = "/images/logo.png"

[markup.goldmark.renderer]
unsafe = true

# Add languages in alphabetical order by language code.
# Link sub-codes of the language code with underscore.
# Write the language name in that language.
[languages]
[languages.ca]
contentDir = "content/ca"
languageName = "Català"
weight = 1
[languages.en]
contentDir = "content/en"
languageName = "English"
weight = 2
[languages.es_MX]
contentDir = "content/es_MX"
languageName = "Español (México)"
weight = 3
[languages.fr]
contentDir = "content/fr"
languageName = "Français"
weight = 4
[languages.hu]
contentDir = "content/hu"
languageName = "Magyar"
weight = 5
[languages.id]
contentDir = "content/id"
languageName = "Bahasa Indonesia"
weight = 6
[languages.ja]
contentDir = "content/ja"
languageName = "日本語"
weight = 7
[languages.ko]
contentDir = "content/ko"
languageName = "한국어"
weight = 8
[languages.zh_CN]
contentDir = "content/zh_CN"
languageName = "中文 (大陆简体)"
weight = 9
[languages.zh_HK]
contentDir = "content/zh_HK"
languageName = "中文 (港澳繁體)"
weight = 10
